-- ============================================================
-- 0105_admin_seed_content.sql
-- One-time data migration: real first-look-content-system Google
-- Sheet content (Bank tabs, Prompts tab, Schedule tabs Sep-Dec 2026)
-- as starting data for the admin dashboard. Purely additive INSERTs
-- (not a repeatable/destructive reseed) — a plain numbered migration,
-- not a DEMO-SEED-GUARD-style guarded seed script.
-- Applied via MCP like 0100-0104. Hand-paste only — never supabase db push.
-- ============================================================

-- content_bank_items — migrated from first-look-content-system Sheet Bank tabs.
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', '3 costs couples always forget', 'A', 'Every couple I sit down with swears they''ve budgeted for everything. Then the invoices start rolling in. The cake-cutting fee — yes, that''s real, paying someone to slice a cake you already bought. Vendor meals — most contracts require you to feed your photographer, DJ, and coordinator, and it''s rarely itemized up front. And gratuities — tip lines for catering staff, drivers, hair and makeup — they add up faster than people think. None of these are huge alone. Together they can blow a few hundred dollars you never saw coming. Build these three in before you finalize anything else.', '3 videos');
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', 'Headcount catch, 3 weeks out', 'C', 'Three weeks before her wedding, a bride I was working with realized she''d never confirmed final headcount with her caterer. Her guest list had changed twice since the invites went out, and the number on the catering contract was months old. We caught it because everything was already logged in one place — the guest list, the RSVPs, and the caterer''s contract all lived together, so the mismatch jumped out immediately instead of showing up as a surprise bill after the wedding.', 'dont recommend this. the venue always asks for head count and she would have to be up to date on her rsvps for the venue. typically if you dont let venues know they will charge you for the guest count that you booked with. people/planners online would pick this apart as its not normal');
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', 'Vendor booking order', 'A', 'Every couple assumes you book the venue first. I get why — it feels like the anchor. But it''s usually not the vendor with the least room to move. For most of my couples, that''s actually the photographer — the good ones book out a year or more, and they only take one wedding a day. So here''s what I tell people: lock in your venue and your least-flexible vendor around the same time, then build the rest of the timeline off those two dates.', '3 videos');
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', 'RSVP chasing script', 'A', 'If you''re chasing RSVPs by email, stop right now — you''ll wait weeks for a reply, I promise you. Text instead, and keep it stupid short: "Hey! Quick one — can you RSVP for the wedding by [date]? Link here: [link]. Would love to have you there!" Casual, direct, has a deadline, lands somewhere people actually check. Every couple I''ve had switch to texting gets double the response rate in half the time.', 'changed this up completely sorrrry  when should you start reaching out to guests for RSVPs If your deadline is 3 weeks away or less');
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', '3 contract red flags', 'A', 'Before you sign anything with a wedding vendor, check for three things. One — an actual cancellation or reschedule clause, not just a deposit policy. Two — specific deliverables. "Photos will be provided" means nothing legally; you want a number, a timeline, a format. Three — payment due dates with a real grace period, not just "due upon receipt." None of these alone is a dealbreaker. But missing all three? That''s the contract I''d ask questions about before signing.', '1. cancellation - if something unexpected happens with the venue or something completely out of your control make sure you know exactly what happens 2 hidden fees - gratudity, cake cutting fees, set up/clean up, food and bev minimums, servicecharges 3. overtime - how much will you get charged if things go past schedule 4. know exactly what is included - video (raws, drone footage) bar (top shelf)');
insert into content_bank_items (platform, idea, type, body, notes) values ('tiktok', 'Budget tracking, side by side', 'D', 'This is what actual-versus-estimated budget tracking looks like inside First Look — and it''s the thing my couples ask me about most. You set your estimate per category up front. As vendors confirm and deposits go out, the actual number updates right next to it, in real time. No separate spreadsheet, no end-of-month reconciliation, no wondering where you stand two weeks out. It''s the one screen I pull up on every client call now.', 'i will do a voice over via tiktok on this');
insert into content_bank_items (platform, idea, format, body) values ('instagram', '3 costs couples always forget', 'Reel — Tip', 'Same spoken script as the TikTok tab — repost natively, don''t re-film. Caption: ''Save this before you build your budget — which one surprised you most?''');
insert into content_bank_items (platform, idea, format, body) values ('instagram', 'Two spreadsheets that didn''t match', 'Carousel — Story', 'Caption: ''Two spreadsheets. Two people. Zero communication. We sat down two months out to reconcile budgets and found a $4k gap — nobody''s fault, just no shared source of truth. Swipe for the fix →'' Slide 2: what went wrong. Slide 3: how it got caught. Slide 4: the one-line takeaway.');
insert into content_bank_items (platform, idea, format, body) values ('instagram', 'Budget tracking feature', 'Static Post — Promo', 'Caption for the Seedream graphic: ''Estimated vs. actual, side by side, updated the second a vendor confirms. No more three spreadsheets that don''t talk to each other. Link in bio.''');
insert into content_bank_items (platform, idea, format, body) values ('instagram', 'Biggest budget worry?', 'Story — Poll', 'Poll prompt only: ''What''s stressing you out most about the wedding budget? Vendor costs / Guest count''');
insert into content_bank_items (platform, idea, format, body) values ('instagram', 'Seating chart redo, the night before', 'Carousel — Story', 'Caption: ''The seating chart got rebuilt at 9pm the night before the wedding. Two families, one last-minute plus-one, and a table that suddenly didn''t fit. Swipe for how it actually got fixed in twenty minutes, not two hours →''');
insert into content_bank_items (platform, idea, format, body) values ('instagram', '3 contract red flags', 'Static Post — Tip', 'Caption: ''Read your vendor contract for these 3 things before you sign ✁️ 1) Cancellation/reschedule terms 2) Specific, numbered deliverables 3) Payment due dates with a grace period. Save this for contract night.''');
insert into content_bank_items (platform, idea, format, body) values ('facebook', '3 costs couples always forget', 'Video Repost — Tip (Page)', 'Same video as TikTok/Reel. Caption: ''Save this before you build your budget''');
insert into content_bank_items (platform, idea, format, body) values ('facebook', 'Two spreadsheets that didn''t match', 'Native Text — Story (Group)', 'Full written post, no video: ''Had a couple last year who were both quietly keeping their own budget spreadsheet. Neither knew the other existed. Two months out, we sat down to reconcile and found a $4,000 gap — nobody''s fault, just no shared source of truth between two people planning the same wedding. If you''re managing your budget solo right now, ask your partner to actually look at the numbers with you this week, not just nod along.''');
insert into content_bank_items (platform, idea, format, body) values ('facebook', 'Vendor went quiet before final payment', 'Native Text — Story (Group)', 'Full written post: ''A vendor went radio silent for two weeks right before a final payment was due. No confirmation on arrival time, no response to three emails. Here''s what actually worked: one direct phone call, referencing the contract''s payment terms specifically, asking for written confirmation by end of day. Got a response in an hour. If you''re in a similar spot — call, don''t just email again.''');
insert into content_bank_items (platform, idea, format, body) values ('facebook', 'Budget tracking feature', 'Video Repost — Promo (Page)', 'Same video as TikTok/IG. Caption: ''This is what actual-vs-estimated budget tracking looks like — one place, always up to date. Link in bio.''');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', 'Budget tracking feature', 'Wedding Budget Tracker: Estimated vs. Actual Cost Guide', 'Track your wedding budget the easy way — see estimated vs. actual costs update in real time as vendors confirm. Perfect for brides planning on a budget.');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', '3 costs couples always forget', '3 Hidden Wedding Costs Every Bride Forgets to Budget For', 'Cake-cutting fees, vendor meals, gratuities — the wedding budget line items couples miss most. Save this before you finalize your wedding budget checklist.');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', '3 contract red flags', 'Wedding Vendor Contract Red Flags to Watch For Before You Sign', '3 things to check in any wedding vendor contract before signing — cancellation terms, specific deliverables, and payment due dates. A must-read before contract night.');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', 'RSVP chasing script', 'The Wedding RSVP Text That Actually Gets People to Respond', 'Stop chasing wedding RSVPs by email. Copy this exact text script to get guests responding fast — perfect for your wedding guest list checklist.');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', 'Vendor booking order', 'What Order to Book Your Wedding Vendors In (It''s Not Venue First)', 'The real wedding vendor booking timeline — why your photographer might need to be locked in before your venue. Save for your wedding planning checklist.');
insert into content_bank_items (platform, idea, title, body) values ('pinterest', 'Real wedding budget breakdown', 'Real Wedding Budget Breakdown: Estimated vs. Actual Costs', 'A real wedding budget, category by category — what was estimated vs. what it actually cost. Great starting point for your own wedding budget planning.');
insert into content_bank_items (platform, idea, format, body) values ('linkedin', 'Inquiry response-time benchmark', 'Text Post — Tip', 'The inquiry response-time benchmark that actually correlates with booking rate: couples who hear back within an hour are significantly more likely to book than couples who wait a day. Most planners lose leads not on price, but on speed. If your average response time is over 4 hours, that''s the first thing worth fixing in your booking process.');
insert into content_bank_items (platform, idea, format, body) values ('linkedin', 'Building-in-public origin story', 'Text Post — Story', 'A note from our founder: I built First Look after watching my wife juggle five separate client threads — texts, emails, spreadsheets, PDFs — just to keep one wedding on track. Multiply that by every client on her books at once. The tools weren''t the problem; the fragmentation was. That''s the thing we set out to fix.');
insert into content_bank_items (platform, idea, format, body) values ('linkedin', 'Events by Jordyn case study', 'Text Post — Case Study', 'A vendor double-booking almost became a client problem two weeks before a wedding. It didn''t, because the conflict showed up the moment both vendors'' confirmed times were logged against the same shared timeline — not buried in two separate email threads. Catching problems like this before the client ever hears about them is the actual job.');
insert into content_bank_items (platform, idea, format, body) values ('linkedin', 'Lead follow-up cadence', 'Text Post — Tip', 'The lead follow-up cadence that keeps inquiries from going cold: same-day acknowledgment, a real follow-up within 48 hours, and one more check-in around the 2-week mark if you haven''t heard back. Most planners have the first step down and drop off after that — the second and third touches are where bookings actually get won.');
insert into content_bank_items (platform, idea, format, body) values ('linkedin', 'Feature announcement', 'Text Post — Announcement (rare)', 'New in First Look this month: shared vendor timelines that update in real time as details get confirmed, so you and your couples are always looking at the same information. A small change, but it removes one of the most common sources of miscommunication we heard about from planners.');

-- admin_automation_prompts — migrated from the Sheet's Prompts tab.
insert into admin_automation_prompts (name, prompt_template) values ('New content-day batch', 'Content day is coming up. Give me 5-7 raw video scripts for Jordyn to film in one sitting — mix of Type A tips, Type B stories, one Type C story+plug. Format them ready to paste into the TikTok Bank tab (Idea | Type | Script).');
insert into admin_automation_prompts (name, prompt_template) values ('Turn a TikTok script into IG/FB', 'Here''s a TikTok script from the Bank: [paste]. Give me the Instagram version (Format tag + caption) and the Facebook version (Format tag + caption), matching the existing row style in those tabs.');
insert into admin_automation_prompts (name, prompt_template) values ('Pinterest pin variations', 'Turn this idea into Pinterest pins: [paste idea/script]. Give me 3-5 Pin Title + Pin Description pairs using bride-search keyword language, ready to paste into the Pinterest Bank tab.');
insert into admin_automation_prompts (name, prompt_template) values ('LinkedIn post draft', 'Draft a LinkedIn post for [business-ops tip / building-in-public story / Events by Jordyn case study / feature announcement]. Format it ready to paste into the LinkedIn Bank tab (Idea | Format | Post Copy).');
insert into admin_automation_prompts (name, prompt_template) values ('Fill next month''s Schedule tab', 'Build me a new Schedule tab for [month] following the same weekly checkbox/Performance-row format as the existing tabs.');
insert into admin_automation_prompts (name, prompt_template) values ('Monthly performance read', 'Here''s this month''s filled-in Performance rows from the Schedule tabs: [paste or summarize]. Tell me which platforms and content types are actually driving DMs/sign-ups, and whether the Type A/B/C/D mix needs adjusting.');

-- Generated from first-look-content-system Sheet (Schedule tabs Sep-Dec 2026).
-- Weeks keyed by start_date; days linked via subquery on schedule_weeks.start_date.

insert into schedule_weeks (label, start_date, end_date) values ('Tue 9/1 – Sun 9/6', '2026-09-01', '2026-09-06');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 9/7 – Sun 9/13', '2026-09-07', '2026-09-13');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 9/14 – Sun 9/20', '2026-09-14', '2026-09-20');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 9/21 – Sun 9/27', '2026-09-21', '2026-09-27');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 9/28 – Wed 9/30', '2026-09-28', '2026-09-30');
insert into schedule_weeks (label, start_date, end_date) values ('Thu 10/1 – Sun 10/4', '2026-10-01', '2026-10-04');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 10/5 – Sun 10/11', '2026-10-05', '2026-10-11');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 10/12 – Sun 10/18', '2026-10-12', '2026-10-18');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 10/19 – Sun 10/25', '2026-10-19', '2026-10-25');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 10/26 – Sat 10/31', '2026-10-26', '2026-10-31');
insert into schedule_weeks (label, start_date, end_date) values ('Sun 11/1 – Sun 11/1', '2026-11-01', '2026-11-01');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 11/2 – Sun 11/8', '2026-11-02', '2026-11-08');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 11/9 – Sun 11/15', '2026-11-09', '2026-11-15');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 11/16 – Sun 11/22', '2026-11-16', '2026-11-22');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 11/23 – Sun 11/29', '2026-11-23', '2026-11-29');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 11/30 – Mon 11/30', '2026-11-30', '2026-11-30');
insert into schedule_weeks (label, start_date, end_date) values ('Tue 12/1 – Sun 12/6', '2026-12-01', '2026-12-06');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 12/7 – Sun 12/13', '2026-12-07', '2026-12-13');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 12/14 – Sun 12/20', '2026-12-14', '2026-12-20');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 12/21 – Sun 12/27', '2026-12-21', '2026-12-27');
insert into schedule_weeks (label, start_date, end_date) values ('Mon 12/28 – Thu 12/31', '2026-12-28', '2026-12-31');

insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-01', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-02', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-03', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-04', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-05', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-06', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-07', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, '3 costs couples forget', 'Inquiry response-time post' from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-08', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-09', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, 'Headcount catch (story+plug)', null from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-10', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, 'Planner-group pass (Jordyn)' from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-11', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-12', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-13', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-14', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-15', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-16', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-17', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-18', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-19', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-20', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-21', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-22', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-23', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-24', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-25', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-26', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-27', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-28', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-29', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-09-30', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-09-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-01', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-02', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-03', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-04', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-05', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-06', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-07', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-08', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-09', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-10', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-11', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-05';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-12', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-13', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-14', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-15', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-16', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-17', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-18', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-12';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-19', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-20', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-21', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-22', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-23', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-24', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-25', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-19';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-26', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-27', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-28', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-29', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-30', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-10-31', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-10-26';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-01', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-02', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-03', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-04', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-05', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-06', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-07', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-08', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-02';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-09', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-10', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-11', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-12', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-13', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-14', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-15', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-09';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-16', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-17', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-18', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-19', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-20', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-21', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-22', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-16';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-23', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-24', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-25', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-26', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-27', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-28', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-29', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-23';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-11-30', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-11-30';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-01', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-02', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-03', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-04', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-05', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-06', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-01';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-07', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-08', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-09', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-10', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-11', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-12', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-13', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-07';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-14', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-15', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-16', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-17', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-18', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-19', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-20', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-14';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-21', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-22', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-23', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-24', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-25', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-26', '{"tiktok": "pending", "ig": "pending", "fbPage": "off", "fbGroups": "off", "pinterest": "pending", "linkedin": "off", "reddit": "pending", "youtube": "off", "outreach": "off"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-27', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "off", "linkedin": "off", "reddit": "off", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-21';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-28', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-29', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-30', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "off", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-28';
insert into schedule_days (week_id, date, platforms, notes_couples, notes_planner) select id, '2026-12-31', '{"tiktok": "pending", "ig": "pending", "fbPage": "pending", "fbGroups": "pending", "pinterest": "pending", "linkedin": "pending", "reddit": "pending", "youtube": "pending", "outreach": "pending"}'::jsonb, null, null from schedule_weeks where start_date = '2026-12-28';

insert into schedule_performance (week_id, views, follower_growth, dms, signups, notes) select id, '14.2k', '+38', '6', '2', 'Story+plug budget post (IG) drove most saves & DMs' from schedule_weeks where start_date = '2026-09-07';
